# File: client.yml
# Date: 22-Feb-2023
#
# Config file for client-side utilities
---
configuration:
  # These must match server-side settings
  JWT_SUBJECT: aTestSubject
  JWT_ALGORITHM: HS256
  JWT_SECRET: aTestSecret
  JWT_DURATION: 300
  JWT_DISABLE: jwtDisable
  #
  # client-to-server specific settings
  SERVER_HOST_AND_PORT: http://0.0.0.0:8000
  CHUNK_SIZE: 8388608  # 8 MB (1024 * 1024 * 8)
  HASH_TYPE: MD5
