# File: config.yml
# Date: 6-Mar-2022
#
# Config file for File Access API server
---
configuration:
  JWT_SUBJECT: aTestSubject
  JWT_ALGORITHM: HS256
  JWT_SECRET: aTestSecret
  JWT_DURATION: 300
  JWT_DISABLE: jwtDisable
  SESSION_DIR_PATH: rcsb/app/tests-file/data/sessions
  REPOSITORY_DIR_PATH: rcsb/app/tests-file/data/repository
  SHARED_LOCK_PATH: rcsb/app/tests-file/data/shared-locks
  PDBX_REPOSITORY: rcsb/app/tests-file/data/mmcif
  KV_MODE: redis
  KV_SESSION_TABLE_NAME: sessions
  KV_LOG_TABLE_NAME: log
  KV_MAX_SECONDS: 14400
  KV_FILE_PATH: ./kv.sqlite
  MILESTONE_LIST: ['upload', 'upload-convert', 'deposit', 'annotate', 'release', 'review']
  REPO_TYPE_LIST: ['deposit', 'archive', 'workflow', 'session']
